# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 -m gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
